const express = require("express");
const { createBooking, getAllBookings, getUserBookings, getBookingsByArtist, updateBooking, getBookingById, artistAdminUpdateBookingStatus, getUserPastBookings, getUserUpcomingBookings, cancelBooking, verifyPayment, getVerifiedPayments, createPendingPaymentOrder, verifyPendingPayment } = require("../controllers/bookingControllers");
const { verifyToken } = require("../middlewares/verifyToken");
const router = express.Router();
router.post("/create-booking",verifyToken, createBooking);
router.post("/verify-booking", verifyPayment);
router.post("/pending-payments", createPendingPaymentOrder);
router.post("/verify-pending-payment", verifyPendingPayment)
router.get("/all-bookings",verifyToken, getAllBookings); 
router.get("/payments", verifyToken, getVerifiedPayments);
//router.get("/bookings/:booking_id",verifyToken, getBookingById); 
router.get("/bookings/:booking_id", getBookingById); 
router.get("/user-bookings/:user_id",verifyToken, getUserBookings);
router.get("/artist-bookings/:artist_id",verifyToken, getBookingsByArtist); 
router.put("/bookings/update/:booking_id",verifyToken,updateBooking);
router.put("/booking/update-status/:booking_id", verifyToken, artistAdminUpdateBookingStatus);
router.get("/past-bookings/:user_id", verifyToken, getUserPastBookings);
router.get("/upcoming-bookings/:user_id", verifyToken, getUserUpcomingBookings);
router.put("/cancel-booking/:booking_id/:user_id", verifyToken,cancelBooking );
module.exports = router;